name: Android CI
# From DroidKaigi 2022 official app
# https://github.com/DroidKaigi/conference-app-2022

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run android lint
        run: ./gradlew lintDebug

      - name: Upload android lint results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: android-lint-results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.txt
            **/build/reports/lint-results-*.xml
          if-no-files-found: error
          retention-days: 14

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.2/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run ktlint
        run: ktlint --reporter=checkstyle,output=build/ktlint-results.xml
        continue-on-error: true

      - name: Upload ktlint results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ktlint-results
          path: |
            **/build/ktlint-results.xml
          if-no-files-found: error
          retention-days: 14

      - name: Run unit test
        run: ./gradlew testDebug

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload apk file
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
