name: Android CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run android lint
        run: ./gradlew lintDebug

#      - name: Show android lint results on GitHub
#        uses: yutailang0119/action-android-lint@v3
#        with:
#          report-path: build/reports/*.xml
#        continue-on-error: false

      - name: Upload android lint results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: android-lint-results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
          if-no-files-found: error
          retention-days: 14

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.2/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run ktlint
        run: ktlint --reporter=checkstyle,output=build/ktlint-results.xml
        continue-on-error: true

      - name: Show ktlint results on GitHub
        uses: yutailang0119/action-ktlint@v3
        with:
          xml_path: build/ktlint-results.xml

      - name: Upload ktlint results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ktlint-results
          path: |
            **/build/ktlint-results.xml
          if-no-files-found: error
          retention-days: 14

      - name: Run unit test
        run: ./gradlew testDebug

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload apk file
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
